name: Deploy WordPress Theme to Azure Web App - campusafetywp
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deployment package
        run: |
          mkdir -p deploy/wp-content/themes/campusafety
          # Use rsync to copy all files except the deploy folder itself
          rsync -av --exclude='deploy' ./ deploy/wp-content/themes/campusafety/
          rm -rf deploy/wp-content/themes/campusafety/.github
          cd deploy
          zip -r release.zip .
          cd ..
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: wordpress-theme
          path: deploy/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wordpress-theme

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'campusafetywp'
          slot-name: 'staging'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D533ACC9B8F54F68BECB674602EC9B33 }}
